In [1]:
import pandas as pd

df = pd.read_csv("WOS.csv")

In [2]:
df.head(5)

,ID,Publication Type,Article Title,Source Title,Conference Title,Abstract
0,1,C,Enhancing Visual Information Extraction with L...,"PATTERN RECOGNITION AND COMPUTER VISION, PRCV ...",7th Chinese Conference on Pattern Recognition ...,"Recently, leveraging large language models (LL..."
1,2,C,FetalExtract-LLM: Structured Information Extra...,"PERINATAL, PRETERM AND PAEDIATRIC IMAGE ANALYS...",10th International Workshop on Perinatal Prete...,Magnetic resonance imaging (MRI) is essential ...
2,3,J,Leveraging Generative AI and Large Language Mo...,KOREAN JOURNAL OF CHEMICAL ENGINEERING,NaN,Process systems engineering (PSE) has long bee...
3,4,J,Use of Machine Learning and Large Language Mod...,ANNUAL REVIEW OF CHEMICAL AND BIOMOLECULAR ENG...,NaN,Rich information in the chemical literature pr...
4,5,J,THE INTEGRATION OF GENERATIVE ARTIFICIAL INTEL...,PRISMA SOCIAL,NaN,The field of artificial intelligence (AI) has ...

In [3]:
# Keep only required columns
df = df.rename(columns={
    "Article Title": "title",
    "Abstract": "abstract"
})

df = df[["title", "abstract"]]

df.to_csv("papers_asreview.csv", index=False)

In [4]:
df.head()

,title,abstract
0,Enhancing Visual Information Extraction with L...,"Recently, leveraging large language models (LL..."
1,FetalExtract-LLM: Structured Information Extra...,Magnetic resonance imaging (MRI) is essential ...
2,Leveraging Generative AI and Large Language Mo...,Process systems engineering (PSE) has long bee...
3,Use of Machine Learning and Large Language Mod...,Rich information in the chemical literature pr...
4,THE INTEGRATION OF GENERATIVE ARTIFICIAL INTEL...,The field of artificial intelligence (AI) has ...

In [10]:
from asreview.io import load_dataset

dataset = load_dataset("papers_asreview.csv")

project.add_dataset(dataset)

c:\Users\ikaqu\Desktop\PROJECT\automatic-SLR\.venv\Lib\site-packages\asreview\utils.py:21: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

ImportError: cannot import name 'load_dataset' from 'asreview.io' (c:\Users\ikaqu\Desktop\PROJECT\automatic-SLR\.venv\Lib\site-packages\asreview\io\__init__.py)